## Hello.
I do something.

[Website link](https://rightmouse.click), [fediverse link](https://linuxrocks.online/@atlas_core)

<!--
**AtlasC0R3/AtlasC0R3** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

I'm keeping this in for a reference for later.
-->

<img align="center" src="https://github-readme-stats.vercel.app/api?username=atlasc0r3&show_icons=true&theme=cobalt" />
<img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=atlasc0r3&exclude_repo=atlasc0r3.github.io&layout=compact&theme=cobalt" />

![Last.fm stats](https://lastfm-recently-played.vercel.app/api?user=atlas_core&loved=true&loved_style=3&width=600)
